import AboutViewVue from '@/views/AboutView.vue';
import { createRouter, createWebHistory } from 'vue-router';
import MagasinUser from '@/components/principal/MagasinUser.vue';import TypeRam from '@/components/principal/TypeRam.vue';import Ram from '@/components/principal/Ram.vue';import TypeDisque from '@/components/principal/TypeDisque.vue';import Disque from '@/components/principal/Disque.vue';import Marque from '@/components/principal/Marque.vue';import Laptop from '@/components/principal/Laptop.vue';import Processeur from '@/components/principal/Processeur.vue';import StockLaptopMagasin from '@/components/principal/StockLaptopMagasin.vue';import PointVente from '@/components/principal/PointVente.vue';import TransfertLaptop from '@/components/principal/TransfertLaptop.vue';import StockPointVente from '@/components/principal/StockPointVente.vue';
import NewMagasinUser from '@/components/principal/NewMagasinUser.vue';import NewTypeRam from '@/components/principal/NewTypeRam.vue';import NewRam from '@/components/principal/NewRam.vue';import NewTypeDisque from '@/components/principal/NewTypeDisque.vue';import NewDisque from '@/components/principal/NewDisque.vue';import NewMarque from '@/components/principal/NewMarque.vue';import NewLaptop from '@/components/principal/NewLaptop.vue';import NewProcesseur from '@/components/principal/NewProcesseur.vue';import NewStockLaptopMagasin from '@/components/principal/NewStockLaptopMagasin.vue';import NewPointVente from '@/components/principal/NewPointVente.vue';import NewTransfertLaptop from '@/components/principal/NewTransfertLaptop.vue';import NewStockPointVente from '@/components/principal/NewStockPointVente.vue';
import ModifMagasinUser from '@/components/principal/ModifMagasinUser.vue';import ModifTypeRam from '@/components/principal/ModifTypeRam.vue';import ModifRam from '@/components/principal/ModifRam.vue';import ModifTypeDisque from '@/components/principal/ModifTypeDisque.vue';import ModifDisque from '@/components/principal/ModifDisque.vue';import ModifMarque from '@/components/principal/ModifMarque.vue';import ModifLaptop from '@/components/principal/ModifLaptop.vue';import ModifProcesseur from '@/components/principal/ModifProcesseur.vue';import ModifStockLaptopMagasin from '@/components/principal/ModifStockLaptopMagasin.vue';import ModifPointVente from '@/components/principal/ModifPointVente.vue';import ModifTransfertLaptop from '@/components/principal/ModifTransfertLaptop.vue';import ModifStockPointVente from '@/components/principal/ModifStockPointVente.vue';

const router = createRouter({
  history: createWebHistory(import.meta.env.BASE_URL),
  routes: [ { path: '/allMagasinUser', name: 'allMagasinUser', component: MagasinUser },{ path: '/allTypeRam', name: 'allTypeRam', component: TypeRam },{ path: '/allRam', name: 'allRam', component: Ram },{ path: '/allTypeDisque', name: 'allTypeDisque', component: TypeDisque },{ path: '/allDisque', name: 'allDisque', component: Disque },{ path: '/allMarque', name: 'allMarque', component: Marque },{ path: '/allLaptop', name: 'allLaptop', component: Laptop },{ path: '/allProcesseur', name: 'allProcesseur', component: Processeur },{ path: '/allStockLaptopMagasin', name: 'allStockLaptopMagasin', component: StockLaptopMagasin },{ path: '/allPointVente', name: 'allPointVente', component: PointVente },{ path: '/allTransfertLaptop', name: 'allTransfertLaptop', component: TransfertLaptop },{ path: '/allStockPointVente', name: 'allStockPointVente', component: StockPointVente },, { path: '/newMagasinUser', name: 'newMagasinUser', component: NewMagasinUser },{ path: '/newTypeRam', name: 'newTypeRam', component: NewTypeRam },{ path: '/newRam', name: 'newRam', component: NewRam },{ path: '/newTypeDisque', name: 'newTypeDisque', component: NewTypeDisque },{ path: '/newDisque', name: 'newDisque', component: NewDisque },{ path: '/newMarque', name: 'newMarque', component: NewMarque },{ path: '/newLaptop', name: 'newLaptop', component: NewLaptop },{ path: '/newProcesseur', name: 'newProcesseur', component: NewProcesseur },{ path: '/newStockLaptopMagasin', name: 'newStockLaptopMagasin', component: NewStockLaptopMagasin },{ path: '/newPointVente', name: 'newPointVente', component: NewPointVente },{ path: '/newTransfertLaptop', name: 'newTransfertLaptop', component: NewTransfertLaptop },{ path: '/newStockPointVente', name: 'newStockPointVente', component: NewStockPointVente },, { path: '/modifMagasinUser', name: 'modifMagasinUser', component: ModifMagasinUser },{ path: '/modifTypeRam', name: 'modifTypeRam', component: ModifTypeRam },{ path: '/modifRam', name: 'modifRam', component: ModifRam },{ path: '/modifTypeDisque', name: 'modifTypeDisque', component: ModifTypeDisque },{ path: '/modifDisque', name: 'modifDisque', component: ModifDisque },{ path: '/modifMarque', name: 'modifMarque', component: ModifMarque },{ path: '/modifLaptop', name: 'modifLaptop', component: ModifLaptop },{ path: '/modifProcesseur', name: 'modifProcesseur', component: ModifProcesseur },{ path: '/modifStockLaptopMagasin', name: 'modifStockLaptopMagasin', component: ModifStockLaptopMagasin },{ path: '/modifPointVente', name: 'modifPointVente', component: ModifPointVente },{ path: '/modifTransfertLaptop', name: 'modifTransfertLaptop', component: ModifTransfertLaptop },{ path: '/modifStockPointVente', name: 'modifStockPointVente', component: ModifStockPointVente }, { path: '/about', name: 'about', component: AboutViewVue }
  ]
})

export default router
